-- 코드를 입력하세요
WITH MILK_TABLE AS (
    SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'),

YOGURT_TABLE AS (
    SELECT DISTINCT CART_ID, NAME
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt')
    
SELECT M.CART_ID
FROM MILK_TABLE AS M 
JOIN YOGURT_TABLE AS Y ON M.CART_ID = Y.CART_ID
ORDER BY M.CART_ID