-- 코드를 입력하세요
SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES AS A, (
    SELECT HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID) >= 2
) AS B
WHERE A.HOST_ID = B.HOST_ID 
ORDER BY A.ID