-- 코드를 입력하세요
# 1. JOIN
# 2. 2022-04-13 AND 흉부외과(CS) AND 취소(N)
# 3. 진료예약일시(APNT_YMD) 오름차순 정렬

SELECT A.APNT_NO, P.PT_NAME, A.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD
FROM APPOINTMENT AS A
JOIN PATIENT AS P ON A.PT_NO = P.PT_NO
JOIN DOCTOR AS D ON A.MDDR_ID = D.DR_ID
WHERE DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = "2022-04-13"
    AND A.MCDP_CD = "CS"
    AND APNT_CNCL_YN  = "N"
ORDER BY A.APNT_YMD