-- 코드를 입력하세요
WITH REVIEW_COUNT AS (
    -- 회원별 리뷰 개수 계산
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
TOP_REVIEWER AS (
    -- 최대 리뷰 개수를 가진 회원 찾기
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT) FROM REVIEW_COUNT)
)
SELECT P.MEMBER_NAME, T.REVIEW_TEXT, DATE_FORMAT(T.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS P
JOIN REST_REVIEW AS T ON P.MEMBER_ID = T.MEMBER_ID
JOIN TOP_REVIEWER AS TR ON T.MEMBER_ID = TR.MEMBER_ID
ORDER BY REVIEW_DATE ASC, T.REVIEW_TEXT ASC;
